// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(OSX)
  import AppKit.NSImage
  internal typealias AssetColorTypeAlias = NSColor
  internal typealias AssetImageTypeAlias = NSImage
#elseif os(iOS) || os(tvOS) || os(watchOS)
  import UIKit.UIImage
  internal typealias AssetColorTypeAlias = UIColor
  internal typealias AssetImageTypeAlias = UIImage
#endif

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
internal enum Asset {
  internal static let goalLockIcon = ImageAsset(name: "goalLockIcon")
  internal static let plusGoal = ImageAsset(name: "plusGoal")
  internal static let plusTodayActions = ImageAsset(name: "plusTodayActions")
  internal static let rocketEmptyIcon = ImageAsset(name: "rocketEmptyIcon")
  internal static let stakeOval = ImageAsset(name: "stakeOval")
  internal static let stakePlay = ImageAsset(name: "stakePlay")
  internal static let stakeShapeBlue = ImageAsset(name: "stakeShapeBlue")
  internal static let stakeShapeWtite = ImageAsset(name: "stakeShapeWtite")
  internal static let actionAdd = ImageAsset(name: "actionAdd")
  internal static let actionBackground = ImageAsset(name: "actionBackground")
  internal static let actionClock = ImageAsset(name: "actionClock")
  internal static let actionDownload = ImageAsset(name: "actionDownload")
  internal static let actionDownloaded = ImageAsset(name: "actionDownloaded")
  internal static let actionImage = ImageAsset(name: "actionImage")
  internal static let actionInfo = ImageAsset(name: "actionInfo")
  internal static let actionLike = ImageAsset(name: "actionLike")
  internal static let actionLiked = ImageAsset(name: "actionLiked")
  internal static let actionLock = ImageAsset(name: "actionLock")
  internal static let actionUnlock = ImageAsset(name: "actionUnlock")
  internal static let actionUnlockBackground = ImageAsset(name: "actionUnlockBackground")
  internal static let actionUnlockIcon = ImageAsset(name: "actionUnlockIcon")
  internal static let musicBackground = ImageAsset(name: "musicBackground")
  internal static let plusBlueIcon = ImageAsset(name: "plusBlueIcon")
  internal static let addActionPlus = ImageAsset(name: "AddActionPlus")
  internal static let addActionShape = ImageAsset(name: "AddActionShape")
  internal static let accessoryIcon = ImageAsset(name: "accessoryIcon")
  internal static let addActionColor = ImageAsset(name: "addActionColor")
  internal static let addActionDuration = ImageAsset(name: "addActionDuration")
  internal static let addActionEndTime = ImageAsset(name: "addActionEndTime")
  internal static let addActionGoal = ImageAsset(name: "addActionGoal")
  internal static let addActionHeader = ImageAsset(name: "addActionHeader")
  internal static let addActionIcons = ImageAsset(name: "addActionIcons")
  internal static let addActionReminder = ImageAsset(name: "addActionReminder")
  internal static let addActionShare = ImageAsset(name: "addActionShare")
  internal static let addActionStake = ImageAsset(name: "addActionStake")
  internal static let addActionStartTime = ImageAsset(name: "addActionStartTime")
  internal static let editDisableIcon = ImageAsset(name: "editDisableIcon")
  internal static let editEnableIcon = ImageAsset(name: "editEnableIcon")
  internal static let shapeBlueButton = ImageAsset(name: "ShapeBlueButton")
  internal static let shapeWhiteButton = ImageAsset(name: "ShapeWhiteButton")
  internal static let clapIcon = ImageAsset(name: "clapIcon")
  internal static let lockIcon = ImageAsset(name: "lockIcon")
  internal static let shapeOrangeIcon = ImageAsset(name: "shapeOrangeIcon")
  internal static let headerBoldTips = ImageAsset(name: "headerBoldTips")
  internal static let shapeBoldTips = ImageAsset(name: "shapeBoldTips")
  internal static let textBoldTips = ImageAsset(name: "textBoldTips")
  internal static let shapeCitation = ImageAsset(name: "ShapeCitation")
  internal static let activePageControl = ImageAsset(name: "activePageControl")
  internal static let inactivePageControl = ImageAsset(name: "inactivePageControl")
  internal static let shareButton = ImageAsset(name: "shareButton")
  internal static let whiteRectangle = ImageAsset(name: "whiteRectangle")
  internal static let boldManifestMain = ImageAsset(name: "boldManifestMain")
  internal static let feelBackground = ImageAsset(name: "feelBackground")
  internal static let hypnosis = ImageAsset(name: "hypnosis")
  internal static let hypnosisMain = ImageAsset(name: "hypnosisMain")
  internal static let inactiveActBackground = ImageAsset(name: "inactiveActBackground")
  internal static let infoIcon = ImageAsset(name: "infoIcon")
  internal static let leonardo = ImageAsset(name: "leonardo")
  internal static let lessons = ImageAsset(name: "lessons")
  internal static let lessonsMain = ImageAsset(name: "lessonsMain")
  internal static let meditation = ImageAsset(name: "meditation")
  internal static let meditationsMain = ImageAsset(name: "meditationsMain")
  internal static let peptalks = ImageAsset(name: "peptalks")
  internal static let peptalksMain = ImageAsset(name: "peptalksMain")
  internal static let quotes = ImageAsset(name: "quotes")
  internal static let serfer = ImageAsset(name: "serfer")
  internal static let stories = ImageAsset(name: "stories")
  internal static let storyMain = ImageAsset(name: "storyMain")
  internal static let homeHeader2Bacground = ImageAsset(name: "homeHeader2Bacground")
  internal static let homeHeaderBackground = ImageAsset(name: "homeHeaderBackground")
  internal static let homeHeaderBigShape = ImageAsset(name: "homeHeaderBigShape")
  internal static let homeHeaderShape = ImageAsset(name: "homeHeaderShape")
  internal static let checkDisableIcon = ImageAsset(name: "checkDisableIcon")
  internal static let checkIcon = ImageAsset(name: "checkIcon")
  internal static let completeToWin = ImageAsset(name: "completeToWin")
  internal static let emotional = ImageAsset(name: "emotional")
  internal static let findJob = ImageAsset(name: "findJob")
  internal static let income = ImageAsset(name: "income")
  internal static let inventSomethings = ImageAsset(name: "inventSomethings")
  internal static let killProject = ImageAsset(name: "killProject")
  internal static let makeDiscovery = ImageAsset(name: "makeDiscovery")
  internal static let marathon = ImageAsset(name: "marathon")
  internal static let masterSkill = ImageAsset(name: "masterSkill")
  internal static let publicSpeech = ImageAsset(name: "publicSpeech")
  internal static let skyDiving = ImageAsset(name: "skyDiving")
  internal static let smoking = ImageAsset(name: "smoking")
  internal static let startNewProject = ImageAsset(name: "startNewProject")
  internal static let startUp = ImageAsset(name: "startUp")
  internal static let triathlon = ImageAsset(name: "triathlon")
  internal static let writeBook = ImageAsset(name: "writeBook")
  internal static let apprentice = ImageAsset(name: "apprentice")
  internal static let intermediate = ImageAsset(name: "intermediate")
  internal static let lock = ImageAsset(name: "lock")
  internal static let risingPower = ImageAsset(name: "risingPower")
  internal static let seasoned = ImageAsset(name: "seasoned")
  internal static let unstoppable = ImageAsset(name: "unstoppable")
  internal static let loader1 = ImageAsset(name: "loader1")
  internal static let loader10 = ImageAsset(name: "loader10")
  internal static let loader100 = ImageAsset(name: "loader100")
  internal static let loader101 = ImageAsset(name: "loader101")
  internal static let loader102 = ImageAsset(name: "loader102")
  internal static let loader103 = ImageAsset(name: "loader103")
  internal static let loader104 = ImageAsset(name: "loader104")
  internal static let loader105 = ImageAsset(name: "loader105")
  internal static let loader106 = ImageAsset(name: "loader106")
  internal static let loader107 = ImageAsset(name: "loader107")
  internal static let loader108 = ImageAsset(name: "loader108")
  internal static let loader109 = ImageAsset(name: "loader109")
  internal static let loader11 = ImageAsset(name: "loader11")
  internal static let loader110 = ImageAsset(name: "loader110")
  internal static let loader111 = ImageAsset(name: "loader111")
  internal static let loader112 = ImageAsset(name: "loader112")
  internal static let loader113 = ImageAsset(name: "loader113")
  internal static let loader114 = ImageAsset(name: "loader114")
  internal static let loader115 = ImageAsset(name: "loader115")
  internal static let loader116 = ImageAsset(name: "loader116")
  internal static let loader117 = ImageAsset(name: "loader117")
  internal static let loader118 = ImageAsset(name: "loader118")
  internal static let loader119 = ImageAsset(name: "loader119")
  internal static let loader12 = ImageAsset(name: "loader12")
  internal static let loader120 = ImageAsset(name: "loader120")
  internal static let loader13 = ImageAsset(name: "loader13")
  internal static let loader14 = ImageAsset(name: "loader14")
  internal static let loader15 = ImageAsset(name: "loader15")
  internal static let loader16 = ImageAsset(name: "loader16")
  internal static let loader17 = ImageAsset(name: "loader17")
  internal static let loader18 = ImageAsset(name: "loader18")
  internal static let loader19 = ImageAsset(name: "loader19")
  internal static let loader2 = ImageAsset(name: "loader2")
  internal static let loader20 = ImageAsset(name: "loader20")
  internal static let loader21 = ImageAsset(name: "loader21")
  internal static let loader22 = ImageAsset(name: "loader22")
  internal static let loader23 = ImageAsset(name: "loader23")
  internal static let loader24 = ImageAsset(name: "loader24")
  internal static let loader25 = ImageAsset(name: "loader25")
  internal static let loader26 = ImageAsset(name: "loader26")
  internal static let loader27 = ImageAsset(name: "loader27")
  internal static let loader28 = ImageAsset(name: "loader28")
  internal static let loader29 = ImageAsset(name: "loader29")
  internal static let loader3 = ImageAsset(name: "loader3")
  internal static let loader30 = ImageAsset(name: "loader30")
  internal static let loader31 = ImageAsset(name: "loader31")
  internal static let loader32 = ImageAsset(name: "loader32")
  internal static let loader33 = ImageAsset(name: "loader33")
  internal static let loader34 = ImageAsset(name: "loader34")
  internal static let loader35 = ImageAsset(name: "loader35")
  internal static let loader36 = ImageAsset(name: "loader36")
  internal static let loader37 = ImageAsset(name: "loader37")
  internal static let loader38 = ImageAsset(name: "loader38")
  internal static let loader39 = ImageAsset(name: "loader39")
  internal static let loader4 = ImageAsset(name: "loader4")
  internal static let loader40 = ImageAsset(name: "loader40")
  internal static let loader41 = ImageAsset(name: "loader41")
  internal static let loader42 = ImageAsset(name: "loader42")
  internal static let loader43 = ImageAsset(name: "loader43")
  internal static let loader44 = ImageAsset(name: "loader44")
  internal static let loader45 = ImageAsset(name: "loader45")
  internal static let loader46 = ImageAsset(name: "loader46")
  internal static let loader47 = ImageAsset(name: "loader47")
  internal static let loader48 = ImageAsset(name: "loader48")
  internal static let loader49 = ImageAsset(name: "loader49")
  internal static let loader5 = ImageAsset(name: "loader5")
  internal static let loader50 = ImageAsset(name: "loader50")
  internal static let loader51 = ImageAsset(name: "loader51")
  internal static let loader52 = ImageAsset(name: "loader52")
  internal static let loader53 = ImageAsset(name: "loader53")
  internal static let loader54 = ImageAsset(name: "loader54")
  internal static let loader55 = ImageAsset(name: "loader55")
  internal static let loader56 = ImageAsset(name: "loader56")
  internal static let loader57 = ImageAsset(name: "loader57")
  internal static let loader58 = ImageAsset(name: "loader58")
  internal static let loader59 = ImageAsset(name: "loader59")
  internal static let loader6 = ImageAsset(name: "loader6")
  internal static let loader60 = ImageAsset(name: "loader60")
  internal static let loader61 = ImageAsset(name: "loader61")
  internal static let loader62 = ImageAsset(name: "loader62")
  internal static let loader63 = ImageAsset(name: "loader63")
  internal static let loader64 = ImageAsset(name: "loader64")
  internal static let loader65 = ImageAsset(name: "loader65")
  internal static let loader66 = ImageAsset(name: "loader66")
  internal static let loader67 = ImageAsset(name: "loader67")
  internal static let loader68 = ImageAsset(name: "loader68")
  internal static let loader69 = ImageAsset(name: "loader69")
  internal static let loader7 = ImageAsset(name: "loader7")
  internal static let loader70 = ImageAsset(name: "loader70")
  internal static let loader71 = ImageAsset(name: "loader71")
  internal static let loader72 = ImageAsset(name: "loader72")
  internal static let loader73 = ImageAsset(name: "loader73")
  internal static let loader74 = ImageAsset(name: "loader74")
  internal static let loader75 = ImageAsset(name: "loader75")
  internal static let loader76 = ImageAsset(name: "loader76")
  internal static let loader77 = ImageAsset(name: "loader77")
  internal static let loader78 = ImageAsset(name: "loader78")
  internal static let loader79 = ImageAsset(name: "loader79")
  internal static let loader8 = ImageAsset(name: "loader8")
  internal static let loader80 = ImageAsset(name: "loader80")
  internal static let loader81 = ImageAsset(name: "loader81")
  internal static let loader82 = ImageAsset(name: "loader82")
  internal static let loader83 = ImageAsset(name: "loader83")
  internal static let loader84 = ImageAsset(name: "loader84")
  internal static let loader85 = ImageAsset(name: "loader85")
  internal static let loader86 = ImageAsset(name: "loader86")
  internal static let loader87 = ImageAsset(name: "loader87")
  internal static let loader88 = ImageAsset(name: "loader88")
  internal static let loader89 = ImageAsset(name: "loader89")
  internal static let loader9 = ImageAsset(name: "loader9")
  internal static let loader90 = ImageAsset(name: "loader90")
  internal static let loader91 = ImageAsset(name: "loader91")
  internal static let loader92 = ImageAsset(name: "loader92")
  internal static let loader93 = ImageAsset(name: "loader93")
  internal static let loader94 = ImageAsset(name: "loader94")
  internal static let loader95 = ImageAsset(name: "loader95")
  internal static let loader96 = ImageAsset(name: "loader96")
  internal static let loader97 = ImageAsset(name: "loader97")
  internal static let loader98 = ImageAsset(name: "loader98")
  internal static let loader99 = ImageAsset(name: "loader99")
  internal static let aaIcon = ImageAsset(name: "aaIcon")
  internal static let addIcon = ImageAsset(name: "addIcon")
  internal static let closeWhite = ImageAsset(name: "closeWhite")
  internal static let downloadIcon = ImageAsset(name: "downloadIcon")
  internal static let headphones = ImageAsset(name: "headphones")
  internal static let likeIcon = ImageAsset(name: "likeIcon")
  internal static let likeRedIcon = ImageAsset(name: "likeRedIcon")
  internal static let playButtonIcon = ImageAsset(name: "playButtonIcon")
  internal static let shareBlueIcon = ImageAsset(name: "shareBlueIcon")
  internal static let menuAct = ImageAsset(name: "menuAct")
  internal static let menuFeel = ImageAsset(name: "menuFeel")
  internal static let menuHome = ImageAsset(name: "menuHome")
  internal static let menuIcon = ImageAsset(name: "menuIcon")
  internal static let menuSettings = ImageAsset(name: "menuSettings")
  internal static let menuThink = ImageAsset(name: "menuThink")
  internal static let menuUser = ImageAsset(name: "menuUser")
  internal static let arrowSwipe = ImageAsset(name: "arrowSwipe")
  internal static let playerBackground = ImageAsset(name: "playerBackground")
  internal static let playerDownloadIcon = ImageAsset(name: "playerDownloadIcon")
  internal static let playerDownloadedIcon = ImageAsset(name: "playerDownloadedIcon")
  internal static let playerLikeIcon = ImageAsset(name: "playerLikeIcon")
  internal static let playerLikedIcon = ImageAsset(name: "playerLikedIcon")
  internal static let playerListIcon = ImageAsset(name: "playerListIcon")
  internal static let playerNext = ImageAsset(name: "playerNext")
  internal static let playerPause = ImageAsset(name: "playerPause")
  internal static let playerPlay = ImageAsset(name: "playerPlay")
  internal static let playerPlayList = ImageAsset(name: "playerPlayList")
  internal static let playerPlusIcon = ImageAsset(name: "playerPlusIcon")
  internal static let playerPrevious = ImageAsset(name: "playerPrevious")
  internal static let playerSmallClose = ImageAsset(name: "playerSmallClose")
  internal static let playerSmallImage = ImageAsset(name: "playerSmallImage")
  internal static let playerSmallPause = ImageAsset(name: "playerSmallPause")
  internal static let playerSmallPlay = ImageAsset(name: "playerSmallPlay")
  internal static let completedIcon = ImageAsset(name: "completedIcon")
  internal static let failedIcon = ImageAsset(name: "failedIcon")
  internal static let profileIcon = ImageAsset(name: "profile_icon")
  internal static let rateApp = ImageAsset(name: "rateApp")
  internal static let rightArrowDownloadsIcon = ImageAsset(name: "rightArrowDownloadsIcon")
  internal static let rightArrowProfileIcon = ImageAsset(name: "rightArrowProfileIcon")
  internal static let starSelected = ImageAsset(name: "starSelected")
  internal static let starUnselected = ImageAsset(name: "starUnselected")
  internal static let threeDotsVertIcon = ImageAsset(name: "threeDotsVertIcon")
  internal static let checkPremiumParams = ImageAsset(name: "checkPremiumParams")
  internal static let checkPremiumSave = ImageAsset(name: "checkPremiumSave")
  internal static let premiumImage = ImageAsset(name: "premiumImage")
  internal static let cardShapeBackground = ImageAsset(name: "cardShapeBackground")
  internal static let downloadLogo = ImageAsset(name: "downloadLogo")
  internal static let emailLogo = ImageAsset(name: "emailLogo")
  internal static let facebookLogo = ImageAsset(name: "facebookLogo")
  internal static let logoBoldShareFriend = ImageAsset(name: "logoBoldShareFriend")
  internal static let shareBackground = ImageAsset(name: "shareBackground")
  internal static let sliderShadowThumb = ImageAsset(name: "SliderShadowThumb")
  internal static let think15 = ImageAsset(name: "Think_1.5")
  internal static let actionShape = ImageAsset(name: "actionShape")
  internal static let appleLogo = ImageAsset(name: "apple_logo")
  internal static let arrowBack = ImageAsset(name: "arrowBack")
  internal static let arrowPopUp = ImageAsset(name: "arrowPopUp")
  internal static let calendarBlueIcon = ImageAsset(name: "calendarBlueIcon")
  internal static let camera = ImageAsset(name: "camera")
  internal static let cameraGrayscale = ImageAsset(name: "cameraGrayscale")
  internal static let charity = ImageAsset(name: "charity")
  internal static let check = ImageAsset(name: "check")
  internal static let checkBox = ImageAsset(name: "checkBox")
  internal static let checkMark = ImageAsset(name: "check_mark")
  internal static let citationBackground = ImageAsset(name: "citationBackground")
  internal static let facebook = ImageAsset(name: "facebook")
  internal static let feelShape = ImageAsset(name: "feelShape")
  internal static let listCalendar = ImageAsset(name: "listCalendar")
  internal static let logoBackground = ImageAsset(name: "logoBackground")
  internal static let logoSmall = ImageAsset(name: "logoSmall")
  internal static let menuBlueIcon = ImageAsset(name: "menuBlueIcon")
  internal static let passwordEye = ImageAsset(name: "passwordEye")
  internal static let passwordEyeOn = ImageAsset(name: "passwordEye_on")
  internal static let plusIcon = ImageAsset(name: "plusIcon")
  internal static let premiumCongrats = ImageAsset(name: "premium_congrats")
  internal static let premiumGirl = ImageAsset(name: "premium_girl")
  internal static let privacyHeader = ImageAsset(name: "privacyHeader")
  internal static let rightArrowIcon = ImageAsset(name: "rightArrowIcon")
  internal static let rightArrowWhite = ImageAsset(name: "rightArrowWhite")
  internal static let screen = ImageAsset(name: "screen")
  internal static let shapeForCell = ImageAsset(name: "shapeForCell")
  internal static let sliderThumb = ImageAsset(name: "sliderThumb")
  internal static let splashBackground = ImageAsset(name: "splashBackground")
  internal static let stakePayment = ImageAsset(name: "stake_payment")
  internal static let starBlue = ImageAsset(name: "star_blue")
  internal static let successKey = ImageAsset(name: "successKey")
  internal static let triangleIcon = ImageAsset(name: "triangleIcon")
  internal static let ulist = ImageAsset(name: "ulist")
  internal static let unlockWhiteIcon = ImageAsset(name: "unlockWhiteIcon")
  internal static let win = ImageAsset(name: "win")
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

internal struct ColorAsset {
  internal fileprivate(set) var name: String

  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, OSX 10.13, *)
  internal var color: AssetColorTypeAlias {
    return AssetColorTypeAlias(asset: self)
  }
}

internal extension AssetColorTypeAlias {
  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, OSX 10.13, *)
  convenience init!(asset: ColorAsset) {
    let bundle = Bundle(for: BundleToken.self)
    #if os(iOS) || os(tvOS)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    self.init(named: NSColor.Name(asset.name), bundle: bundle)
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

internal struct DataAsset {
  internal fileprivate(set) var name: String

  #if os(iOS) || os(tvOS) || os(OSX)
  @available(iOS 9.0, tvOS 9.0, OSX 10.11, *)
  internal var data: NSDataAsset {
    return NSDataAsset(asset: self)
  }
  #endif
}

#if os(iOS) || os(tvOS) || os(OSX)
@available(iOS 9.0, tvOS 9.0, OSX 10.11, *)
internal extension NSDataAsset {
  convenience init!(asset: DataAsset) {
    let bundle = Bundle(for: BundleToken.self)
    #if os(iOS) || os(tvOS)
    self.init(name: asset.name, bundle: bundle)
    #elseif os(OSX)
    self.init(name: NSDataAsset.Name(asset.name), bundle: bundle)
    #endif
  }
}
#endif

internal struct ImageAsset {
  internal fileprivate(set) var name: String

  internal var image: AssetImageTypeAlias {
    let bundle = Bundle(for: BundleToken.self)
    #if os(iOS) || os(tvOS)
    let image = AssetImageTypeAlias(named: name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    let image = bundle.image(forResource: NSImage.Name(name))
    #elseif os(watchOS)
    let image = AssetImageTypeAlias(named: name)
    #endif
    guard let result = image else { fatalError("Unable to load image named \(name).") }
    return result
  }
}

internal extension AssetImageTypeAlias {
  @available(iOS 1.0, tvOS 1.0, watchOS 1.0, *)
  @available(OSX, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init!(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = Bundle(for: BundleToken.self)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

private final class BundleToken {}
